workflow fixes

diff --git a/.github/workflows/check_changelog.yml b/.github/workflows/check_changelog.yml
--- a/.github/workflows/check_changelog.yml
+++ b/.github/workflows/check_changelog.yml
@@ -14,25 +14,26 @@ jobs:
         run: |
           echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
       - uses: actions/checkout@v2
-
-      - name: Check the changelog
-        run: |
-          set -xe
-          git config --global core.whitespace cr-at-eol
-          changed_files=$(git diff --name-only origin/main)
-          if [[ "$changed_files" =~ CHANGELOG\.md ]]
-          then
-            changelog=$(cat ./CHANGELOG.md)
-            if [[ "$changelog" =~ https://github\.com/microsoft/InnerEye-DeepLearning/pull/$PR_NUMBER ]]
-            then
-              echo "Changelog has been updated and contains the PR number."
-            else
-              echo "Changelog has been modified, but does not contain a hyperlink the present PR."
-              echo "Make sure that there is a changelog entry that links to the present PR."
-              echo "If no changelog entry is required for this PR, label the PR with 'no changelog needed'."
-            fi
-          else
-            echo "Each PR needs to summarize the changes in CHANGELOG.md, but this PR does not make any"
-            echo "changes to that file. The changelog entry must contain a hyperlink to the present PR."
-            echo "If no changelog entry is required for this PR, label the PR with 'no changelog needed'."
-          fi
+        with:
+          fetch-depth: '0'
+  - name: Check the changelog
+    run: |
+      set -xe
+      git config --global core.whitespace cr-at-eol
+      changed_files=$(git diff --name-only main)
+      if [[ "$changed_files" =~ CHANGELOG\.md ]]
+      then
+        changelog=$(cat ./CHANGELOG.md)
+        if [[ "$changelog" =~ https://github\.com/microsoft/InnerEye-DeepLearning/pull/$PR_NUMBER ]]
+        then
+          echo "Changelog has been updated and contains the PR number."
+        else
+          echo "Changelog has been modified, but does not contain a hyperlink the present PR."
+          echo "Make sure that there is a changelog entry that links to the present PR."
+          echo "If no changelog entry is required for this PR, label the PR with 'no changelog needed'."
+        fi
+      else
+        echo "Each PR needs to summarize the changes in CHANGELOG.md, but this PR does not make any"
+        echo "changes to that file. The changelog entry must contain a hyperlink to the present PR."
+        echo "If no changelog entry is required for this PR, label the PR with 'no changelog needed'."
+      fi
